name: 'CD - Automation'

on:
  push:

jobs:
  test:
    name: Run Robot Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python for starting the tests
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.12.0'
          architecture: 'x64'

      - name: Setup Install Robot
        run: pip install robotframework-seleniumlibrary

      - name: Run Tests
        run: robot -d results Tests/Playground.robot -v GRID_URL:https://sso-mbio-saucelabs-JOCARV:af0a598d-910f-47f0-b78e-023098c248ea@ondemand.eu-central-1.saucelabs.com:443/wd/hub"

      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: results
          path: results

  generate_report:
      if: always()
      needs: [test]
      name: Generate Report
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: results

      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.3
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report_path: 'results'