name: 'CD - Automation'

on:
  push:

jobs:
  test:
    name: Run Robot Tests
    runs-on: ubuntu-latest
    services:
      chrome-standalone:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
          - 5900:5900
        options: >-
          --shm-size="2g"
          -e SCREEN_WIDTH=1366
          -e SCREEN_HEIGHT=768

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python for starting the tests
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.12.0'
          architecture: 'x64'

      - name: Setup Install Robot
        run: pip install robotframework-seleniumlibrary

      - name: Run Tests
        run: robot -d results Tests/Playground.robot

      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: results
          path: results

  generate_report:
      if: always()
      needs: [test]
      name: Generate Report
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: results

      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.3
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report_path: 'results'